/**
 * Application-level domain types.
 *
 * These mirror the SQL schema in `db/migrations/`. They are hand-written so the
 * repository stays readable without a live database, and each one matches the
 * exact column list its query selects.
 *
 * Note `session_id` where a conventional app would have `user_id`: this
 * deployment is a public demo with no sign-in, and rows are partitioned by an
 * anonymous demo session instead. See `src/lib/session.ts`.
 */

export type DocumentStatus = 'uploaded' | 'processing' | 'ready' | 'failed';

export type FeedbackRating = 'helpful' | 'not_helpful';

export interface DocumentRow {
  id: string;
  session_id: string;
  title: string;
  file_name: string;
  file_size: number;
  content_type: string;
  page_count: number | null;
  status: DocumentStatus;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface DocumentChunkRow {
  id: string;
  document_id: string;
  page_number: number;
  chunk_index: number;
  content: string;
  content_length: number;
  created_at: string;
}

/**
 * One row returned by the `match_document_chunks` function.
 * This is the raw retrieval result, before it is turned into a citation.
 */
export interface MatchedChunk {
  chunk_id: string;
  document_id: string;
  document_title: string;
  file_name: string;
  page_number: number;
  chunk_index: number;
  content: string;
  similarity: number;
}

/**
 * A citation as displayed in the UI and persisted on `questions.sources`.
 *
 * Built by the application from retrieval results -- never generated by the
 * model. See `src/lib/rag/citations.ts`.
 */
export interface Citation {
  /** 1-based index used to label the source card ("1", "2", ...). */
  index: number;
  documentId: string;
  documentTitle: string;
  fileName: string;
  /** 1-based PDF page number, exactly as reported by the PDF parser. */
  pageNumber: number;
  /** The retrieved chunk text (possibly trimmed for display). */
  excerpt: string;
  similarity: number;
}

export interface QuestionRow {
  id: string;
  session_id: string;
  question: string;
  answer: string;
  sources: Citation[];
  response_time_ms: number | null;
  model: string;
  created_at: string;
}

/** History list row: the citation payload is reduced to a count in SQL. */
export interface QuestionSummary {
  id: string;
  question: string;
  answer: string;
  source_count: number;
  created_at: string;
  rating: FeedbackRating | null;
}

/** History detail row: the full question joined with this session's rating. */
export interface QuestionWithFeedback extends QuestionRow {
  rating: FeedbackRating | null;
}

export interface AnswerFeedbackRow {
  id: string;
  question_id: string;
  session_id: string;
  rating: FeedbackRating;
  comment: string | null;
  created_at: string;
  updated_at: string;
}

/** Successful payload of `POST /api/ask`. */
export interface AskSuccessResponse {
  questionId: string;
  question: string;
  answer: string;
  citations: Citation[];
  model: string;
  responseTimeMs: number;
  /** True when retrieval found nothing above the similarity threshold. */
  noRelevantContext: boolean;
}
