/**
 * Application-level domain types.
 *
 * These mirror the SQL schema in `supabase/migrations/`. They are hand-written
 * rather than generated so the repository stays readable without a live
 * Supabase project; `supabase gen types typescript` can replace them once a
 * project is linked (see README).
 */

export type DocumentStatus = 'uploaded' | 'processing' | 'ready' | 'failed';

export type FeedbackRating = 'helpful' | 'not_helpful';

export interface DocumentRow {
  id: string;
  user_id: string;
  title: string;
  file_name: string;
  storage_path: string;
  file_size: number;
  page_count: number | null;
  status: DocumentStatus;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface DocumentChunkRow {
  id: string;
  document_id: string;
  page_number: number;
  chunk_index: number;
  content: string;
  content_length: number;
  created_at: string;
}

/**
 * One row returned by the `match_document_chunks` RPC.
 * This is the raw retrieval result, before it is turned into a citation.
 */
export interface MatchedChunk {
  chunk_id: string;
  document_id: string;
  document_title: string;
  file_name: string;
  page_number: number;
  chunk_index: number;
  content: string;
  similarity: number;
}

/**
 * A citation as displayed in the UI and persisted on `questions.sources`.
 *
 * Built by the application from retrieval results -- never generated by the
 * model. See `src/lib/rag/citations.ts`.
 */
export interface Citation {
  /** 1-based index used to label the source card ("1", "2", ...). */
  index: number;
  documentId: string;
  documentTitle: string;
  fileName: string;
  /** 1-based PDF page number, exactly as reported by the PDF parser. */
  pageNumber: number;
  /** The retrieved chunk text (possibly trimmed for display). */
  excerpt: string;
  similarity: number;
}

export interface QuestionRow {
  id: string;
  user_id: string;
  question: string;
  answer: string;
  sources: Citation[];
  response_time_ms: number | null;
  model: string;
  created_at: string;
}

export interface AnswerFeedbackRow {
  id: string;
  question_id: string;
  user_id: string;
  rating: FeedbackRating;
  comment: string | null;
  created_at: string;
  updated_at: string;
}

export interface QuestionWithFeedback extends QuestionRow {
  feedback: { rating: FeedbackRating } | null;
}

/** Successful payload of `POST /api/ask`. */
export interface AskSuccessResponse {
  questionId: string;
  question: string;
  answer: string;
  citations: Citation[];
  model: string;
  responseTimeMs: number;
  /** True when retrieval found nothing above the similarity threshold. */
  noRelevantContext: boolean;
}
