import { z } from 'zod';

import { MAX_FILE_SIZE_BYTES, MAX_PAGE_COUNT, MAX_UPLOAD_PARTS } from '@/lib/config/rag';
import { userMessageFor, type AppErrorCode } from '@/lib/errors';

/**
 * Upload validation.
 *
 * All pure functions: the same rules run in the browser (for instant feedback)
 * and again on the server (because client-side checks are a UX feature, not a
 * security control).
 */

export const PDF_MIME_TYPE = 'application/pdf';
export const PDF_EXTENSION = '.pdf';

export interface FileValidationInput {
  name: string;
  size: number;
  type: string;
}

export type FileValidationResult =
  | { ok: true }
  | { ok: false; code: AppErrorCode; message: string };

function fail(code: AppErrorCode): FileValidationResult {
  return { ok: false, code, message: userMessageFor(code) };
}

/**
 * Reject anything that is not a plausible PDF within the size budget.
 *
 * MIME type *and* extension are both checked: browsers occasionally report an
 * empty or generic `type`, and a `.pdf` extension alone is trivially forged.
 * The real structural check happens later, when the parser actually opens the
 * file.
 */
export function validatePdfFile(file: FileValidationInput): FileValidationResult {
  const hasPdfExtension = file.name.toLowerCase().endsWith(PDF_EXTENSION);
  const hasPdfMime = file.type === PDF_MIME_TYPE;

  if (!hasPdfExtension || !hasPdfMime) {
    return fail('invalid_file_type');
  }

  if (!Number.isFinite(file.size) || file.size <= 0) {
    return fail('validation_failed');
  }

  if (file.size > MAX_FILE_SIZE_BYTES) {
    return fail('file_too_large');
  }

  return { ok: true };
}

export function validatePageCount(pageCount: number): FileValidationResult {
  if (!Number.isInteger(pageCount) || pageCount < 1) {
    return fail('pdf_unreadable');
  }
  if (pageCount > MAX_PAGE_COUNT) {
    return fail('too_many_pages');
  }
  return { ok: true };
}

/** Display title derived from the filename, keeping the user's original text. */
export function deriveTitle(rawName: string): string {
  const withoutPath = rawName.split(/[/\\]/).pop() ?? rawName;
  const withoutExt = withoutPath.toLowerCase().endsWith(PDF_EXTENSION)
    ? withoutPath.slice(0, -PDF_EXTENSION.length)
    : withoutPath;
  const trimmed = withoutExt.trim();
  return (trimmed || 'Untitled document').slice(0, 300);
}

/**
 * Body of `POST /api/documents/register`.
 *
 * Registration happens *before* the bytes are uploaded, so that the parts have
 * a document row to attach to. `documentId` is generated by the browser, which
 * is safe here because the row is always written with the server-resolved
 * session id -- the worst a caller can do with a chosen id is collide with
 * their own.
 */
export const registerDocumentSchema = z.object({
  documentId: z.string().uuid(),
  title: z.string().trim().min(1).max(300),
  fileName: z.string().trim().min(1).max(300),
  fileSize: z.number().int().positive().max(MAX_FILE_SIZE_BYTES),
});

export type RegisterDocumentInput = z.infer<typeof registerDocumentSchema>;

/** Body of `POST /api/documents/process`. */
export const processDocumentSchema = z.object({
  documentId: z.string().uuid(),
});

/** Query parameters of `POST /api/documents/[id]/parts`. */
export const uploadPartSchema = z.object({
  partIndex: z.number().int().min(0).max(MAX_UPLOAD_PARTS - 1),
});
